name: FASCSA Orders Daily RSS Update

on:
  schedule:
    - cron: '5 5 * * *'  # Runs daily at 12:05 AM EST (05:05 UTC)
  workflow_dispatch:

jobs:
  update-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run script
        run: python generate_rss.py

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin
          git rebase origin/main || echo "No rebase needed"

      - name: Commit and push with retry
        run: |
          git add rss_log.xml rss_items.xml
          git commit -m "Daily RSS update" || echo "No changes to commit"
        continue-on-error: true

      - name: Retry git push
        uses: Wandalen/wretry.action@v1.0.36
        with:
          command: git push
          attempt_limit: 3
          attempt_delay: 5000
